### ISSUE TITLE
CRT Display Aspect Ratio for SNES is NOT 4:3

### ISSUE THREAD

**Issue by Firebrandx** [Marat-Tanalin/bsnes-mt#23]
In reference to this article:

https://tanalin.com/en/projects/bsnes-mt/

The SNES dot clock for it's 256x240p signal sends a display aspect ratio of 128:105 to the CRT (and the CRT when properly calibrated does NOT stretch signal sources to 4:3).

To properly calibrate for CRT aspect correction on the horizontal axis in SNES emulation, you need multiply 256 by 8/7 (which is the pixel aspect ratio). Thus, 8/7 = 1.142857 (repeating) and then you multiply 256 with that, which comes out to 292.571428 (repeating). For emulation, it's even more accurate to scale first before applying the 8/7 PAR correction. Example at 4x:

256 * 4 = 1024, and then applying DAR for CRTs: 1024 * 8/7 = 1170 (rounded to nearest even pixel count).

**Comment by Marat-Tanalin** [comment]
What aspect-ratio-correction approach is more correct was discussed multiple times by multiple people so far. Some people believe 8:7 PAR was used by game developers who did care about aspect ratio, while Afaik, CRT displays stretched the image anyway to the entire screen which was usually 4:3.

240p actually turns into 224p due to cropping the so called overscan area.

There is [info](https://github.com/bsnes-emu/bsnes/issues/175) in the bsnes issue tracker that PAL versions of SNES had a different aspect ratio compared with NTSC versions. Cannot confirm or deny that though.

Anyway, using 8:7 PAR instead of 4:3 DAR is available in bsnes-mt via the corresponding checkbox in the “Settings” → “Output” menu. Note though that in the “Pixel-perfect” scaling mode, there is usually no difference due to rounding of both vertical and horizontal scales to integers and some inevitable aspect-ratio error as a result.

**Comment by Firebrandx** [comment]
"while Afaik, CRT displays stretched the image anyway to the entire screen which was usually 4:3"

That is incorrect. Your entire approach to CRT aspect correction for the SNES is based on bad information. No matter what any given artist did or didn't do does NOT factor into how the SNES was displayed on a CRT, and the CRT does NOT stretch the SNES into a 4:3 image. The SOURCE determines CRT aspect correction, and for the SNES, the 265x240p area is sent at 128:105. Also there is no 'cropping' to 224. Merely most games left the rest of the 240 lines black, but still sends them anyway, so you MUST account for the entire 240p lines. The SNES can in fact draw into those 240 lines. Please read up on dot clocks for consoles here:

https://pineight.com/mw/page/Dot_clock_rates.xhtml

And also my Youtube video on the subject here:

https://www.youtube.com/watch?v=2owtAwcysQI

Near was correct in basing CRT aspect correction on 8:7 pixel aspect ratio, because that's exactly how it worked on a CRT. We've been trying to educate people on this because for YEARS people have been misinformed that a CRT "stretches everything to 4:3". It simply does NOT do that.

**Comment by Marat-Tanalin** [comment]
> Your entire approach to CRT aspect correction for the SNES is based on bad information. 

It’s not just me. Snes9x and other emulators use 4:3 DAR or have it as an option. E.g. Snes9x has two options: 8:7 (256×224) and 4:3.

Compared with bsnes, basically the only thing I added in terms of aspect ratio (besides more accurate calculations in the “Scale” mode) is ability to choose between 8:7 PAR (the only way bsnes does aspect-ratio correction with a resulting DAR of ~1.3) and 4:3 (1.333) DAR.

> Also there is no 'cropping' to 224.

Do you mean that overscan is a myth and authors of bsnes and many other emulators cropped those pixels out by mistake? ;-)

Also, do you take PAL/NTSC differences into account?

In general, thanks for the info and links, I will check them out when I have time.
